BIO_labels = ["B-s1",  "I-s1",
"B-s2",  "I-s2",
"B-s3",  "I-s3",
"B-s5",  "I-s5",
"B-s6",  "I-s6",
"B-s7", "I-s7",
"B-s8", "I-s8",
"B-s9", "I-s9",
"B-m1", "I-m1",
"B-m2", "I-m2",
"B-m3", "I-m3",
"B-m4", "I-m4",
"B-m5", "I-m5",
"B-m6", "I-m6",
"B-m7", "I-m7",
"B-oth", "I-oth",
"O", "C"] # "C" for correction
